services:

  backend:
    build:
      context: ../..
      dockerfile: compose/local/fastapi/dockerfile
    env_file: .env
    depends_on:
      pg_database:
        condition: service_healthy
    ports:
      - "8080:8080"

  pg_database:
    image: postgres:17
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_PASSWORD: ${POSTGRES_APP_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_ADMIN_USER} -d ${POSTGRES_DBNAME}"]
      interval: 30s
      timeout: 30s
      retries: 10

volumes:
  postgres_data:
